// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalNavbar from "@/components/ConditionalNavbar";
import ConditionalFooter from "@/components/ConditionalFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params?: { slug?: string };
}

export default function RootLayout({ children, params }: RootLayoutProps) {
  return (
    <html lang="tr">
      {/* <body>
        <ConditionalNavbar />
        <main key={params?.slug || 'default'}>{children}</main>
        <ConditionalFooter />
      </body> */}


      <body suppressHydrationWarning className="page-layout">
        <ConditionalNavbar />
        <main className="main-content" key={params?.slug || 'default'}>
          {children}
        </main>
        <ConditionalFooter />
      </body>


    </html>
  )
}
